image: atlassian/default-image:3

definitions:
  steps:
    - step: &sync-to-github
        name: Sync to GitHub
        script:
          - echo "Installing Git LFS..."
          - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
          - apt-get update
          - apt-get install -y git-lfs
          - git lfs install
          - echo "Setting up Git configuration..."
          - git config --global user.email "pipeline@bitbucket.org"
          - git config --global user.name "Bitbucket Pipeline"
          - echo "Adding GitHub remote..."
          - git remote add github https://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@github.com/rasitsodec/sodec-identity-platform-saglampay-static.git
          - echo "Current remotes:"
          - git remote -v
          - echo "Fetching latest changes from GitHub..."
          - git fetch github || echo "GitHub fetch failed, continuing..."
          - echo "Pushing branch to GitHub..."
          - |
            if [ -n "$BITBUCKET_BRANCH" ]; then
              git push github $BITBUCKET_BRANCH --force-with-lease
            else
              echo "No branch detected, pushing current HEAD to main..."
              git push github HEAD:main --force-with-lease
            fi
          - echo "Pushing tags to GitHub..."
          - git push github --tags --force-with-lease
          - echo "Checking LFS files..."
          - git lfs ls-files
          - echo "GitHub sync completed successfully!"

pipelines:
  branches:
    main:
      - step: *sync-to-github
  tags:
    '*':
      - step: *sync-to-github 